# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nincal', '0003_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nincal.Option')),
            ],
        ),
        migrations.RemoveField(
            model_name='poll',
            name='value',
        ),
        migrations.AddField(
            model_name='option',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nincal.Poll'),
        ),
    ]
