# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nincal', '0004_auto_20151215_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
